# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'openedx-app-firebase-analytics-ios'
  annotations:
    openedx.org/release: "main"
spec:
  owner: group:rg-mobile
  type: 'mobile'
  lifecycle: 'production'
